services:
  ###########################################################################
  # 🧩 NEXT.JS (Frontend - Escala)
  ###########################################################################
  nextapp:
    container_name: escala-nextapp
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env.local
    environment:
      - WATCHPACK_POLLING=true      # hot-reload estável no Docker
      - CHOKIDAR_USEPOLLING=1
      - PORT=3000
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - API_BASE_URL=http://escala-backend:8080
      - NEXT_PUBLIC_STRAPI_PUBLIC_URL=http://localhost:1337
      - NEXT_INTERNAL_STRAPI_URL=http://cms-strapi:1337
    volumes:
      - ../:/app                    # monta o código-fonte do projeto
      - /app/node_modules           # ignora node_modules do host
    working_dir: /app
    command: pnpm dev
    networks:
      escala-network:

networks:
  escala-network:
    external: true
