services:
  ###########################################################################
  # 🧩 NEXT.JS (Frontend - Escala)
  ###########################################################################
  nextapp:
    container_name: escala-nextapp
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env.local
    environment:
      - WATCHPACK_POLLING=true      # hot-reload estável no Docker
      - CHOKIDAR_USEPOLLING=1
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ../:/app                    # monta o código-fonte do projeto
      - /app/node_modules           # ignora node_modules do host
    working_dir: /app
    command: npm run dev
    networks:
      nino-network:

networks:
  nino-network:
    external: true
