version: "3.9"

services:
  web:
    build: .
    working_dir: /app
    command: npm run dev
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file: .env
    environment:
      - WATCHPACK_POLLING=true     # hot-reload estável no Docker
      - CHOKIDAR_USEPOLLING=1
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./app:/app                 # seu código
      - /app/node_modules          # evita conflito do node_modules
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - myapp_db_data:/var/lib/postgresql/data

volumes:
  myapp_db_data:
